# Generated by Django 3.2.3 on 2021-09-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_role',
        ),
    ]
