# Generated by Django 3.2.3 on 2021-09-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequesits',
            field=models.ManyToManyField(help_text='The course(s) one must pass before taking this course.', to='course_management.Course', verbose_name='Prerequesit Courses'),
        ),
    ]
