# Generated by Django 3.2.3 on 2021-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_course_prerequesits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequesits',
            field=models.ManyToManyField(blank=True, help_text='The course(s) one must pass before taking this course.', to='course_management.Course', verbose_name='Prerequesit Courses'),
        ),
    ]
