# Generated by Django 3.2.3 on 2021-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_alter_course_prerequesits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='term',
        ),
        migrations.AddField(
            model_name='term',
            name='season',
            field=models.CharField(choices=[(1, 'SPRING'), (2, 'SUMMER'), (3, 'FALL'), (4, 'WINTER')], default='FALL', help_text='Term Season', max_length=30, verbose_name='Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, help_text='The day on which the term starts.', verbose_name='Term Start Date'),
        ),
    ]
