# Generated by Django 3.2.3 on 2021-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_auto_20210916_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='season',
            field=models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'SUMMER'), (3, 'FALL'), (4, 'WINTER')], default=1, help_text='Term Season', verbose_name='Season'),
        ),
    ]
