# Generated by Django 3.2.3 on 2021-09-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0007_alter_term_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselog',
            name='final',
        ),
        migrations.RemoveField(
            model_name='courselog',
            name='midterm',
        ),
        migrations.RemoveField(
            model_name='courselog',
            name='status',
        ),
        migrations.AddField(
            model_name='courselog',
            name='final_exam',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The grade of the final exam', verbose_name='Final Exam Grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselog',
            name='midterm_exam',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The grade of the midterm exam', verbose_name='Midterm Exam Grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courselog',
            name='final_grade',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Not Approved', 'Not Approved'), ('Approved', 'Approved')], default='Unavailable', help_text='Designates if the grade is not entered, entered or finalized.', max_length=20, verbose_name='Course Status'),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='public_id',
            field=models.CharField(blank=True, help_text='Public ID to identify an individual course log.', max_length=30, unique=True, verbose_name='Public Course Log ID'),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='section',
            field=models.ForeignKey(help_text='The course section of this class', on_delete=django.db.models.deletion.CASCADE, to='course_management.coursesection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='student',
            field=models.ForeignKey(help_text='The student corresponding to this course log', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='instructor',
            field=models.ForeignKey(help_text='The instructor of the class', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='local_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The identity of the course section among all sections of a course in a term.', verbose_name='Course Section Group'),
        ),
    ]
