# Generated by Django 3.2.3 on 2021-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0009_auto_20210918_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselog',
            name='final_exam',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The grade of the final exam', null=True, verbose_name='Final Exam Grade'),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='final_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The final grade of the course', null=True, verbose_name='Final Grade'),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='midterm_exam',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The grade of the midterm exam', null=True, verbose_name='Midterm Exam Grade'),
        ),
    ]
