# Generated by Django 3.2.3 on 2021-09-19 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0010_auto_20210918_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='global_id',
        ),
        migrations.AddField(
            model_name='complain',
            name='public_id',
            field=models.CharField(blank=True, help_text='Public ID to identify an individual complain.', max_length=30, unique=True, verbose_name='Public Complain ID'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='section',
            field=models.ForeignKey(help_text='The course section of this complain', on_delete=django.db.models.deletion.CASCADE, to='course_management.coursesection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Seen', 'Seen'), ('Unseen', 'Unseen')], default='Unseen', help_text='Designates if the complain is seen by the instructor or not.', max_length=10, verbose_name='Complain Status'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='student',
            field=models.ForeignKey(help_text='The student corresponding to this complain', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='text',
            field=models.TextField(help_text='The text of the complain.', max_length=300, verbose_name='Text'),
        ),
    ]
