# Generated by Django 3.2.3 on 2021-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0011_auto_20210919_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselog',
            name='status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Not Approved', 'Not Approved'), ('Approved', 'Approved')], default='Unavailable', help_text='Designates if the grade is not entered, entered or finalized.', max_length=20, verbose_name='Grade Status'),
        ),
    ]
