# Generated by Django 3.2.3 on 2021-10-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0013_auto_20211014_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='public_id',
            field=models.CharField(blank=True, editable=False, help_text='Public ID to identify an individual complain.', max_length=30, unique=True, verbose_name='Public Complain ID'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Seen', 'Seen'), ('Unseen', 'Unseen')], default='Unseen', editable=False, help_text='Designates if the complain is seen by the instructor or not.', max_length=10, verbose_name='Complain Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.CharField(blank=True, editable=False, help_text='Public ID to identify an individual course.', max_length=30, unique=True, verbose_name='Public Course ID'),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='public_id',
            field=models.CharField(blank=True, editable=False, help_text='Public ID to identify an individual course log.', max_length=30, unique=True, verbose_name='Public Course Log ID'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='local_id',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='The identity of the course section among all sections of a course in a term.', verbose_name='Course Section Group'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='public_id',
            field=models.CharField(blank=True, editable=False, help_text='Public ID to identify an individual course.', max_length=30, unique=True, verbose_name='Public Course Section ID'),
        ),
        migrations.AlterField(
            model_name='term',
            name='public_id',
            field=models.CharField(blank=True, editable=False, help_text='Public ID to identify an individual term.', max_length=30, unique=True, verbose_name='Public Term ID'),
        ),
    ]
